formatting:
  rag:
    empty_message:
      vi: "Không có tài liệu liên quan đến báo cáo tài chính."
  sql:
    empty_message:
      vi: "Không tìm thấy dữ liệu tài chính từ SQL."
  dashboard:
    empty_message:
      vi: "Không có dữ liệu biểu đồ."
    vis_type_templates:
      boxplot:
        vi: "Biểu đồ boxplot thể hiện sự biến động của {value_col} theo {group_col}."
      histogram:
        vi: "Biểu đồ histogram thể hiện phân phối của {value_col}."
      scatter:
        vi: "Biểu đồ scatter thể hiện mối quan hệ giữa {x_col} và {y_col}."
      pie_chart:
        vi: "Biểu đồ tròn thể hiện tỷ lệ của {value_col} theo {category_col}."
      line_chart:
        vi: "Biểu đồ đường thể hiện xu hướng của {y_col} theo {x_col}."
      bar_chart:
        vi: "Biểu đồ cột thể hiện giá trị của {value_col} theo {category_col}."
      table:
        vi: "Bảng dữ liệu hiển thị thông tin chi tiết."
      heatmap:
        vi: "Biểu đồ heatmap thể hiện mối quan hệ giữa các giá trị."
    default_template:
      vi: "Biểu đồ {vis_type} thể hiện dữ liệu."
output_template:
  vi: "{summary}"