visualization_metadata:
  - vis_type: "table"
    description: "Table for displaying raw data"
    columns:
      - name: "columns"
        description: "List of columns to display in the table"
        intent_keywords: ["symbol", "name", "sector", "market_cap", "date", "close_price"]
    templates:
      - name: "single_value"
        description: "Retrieve a single value (e.g., closing price on a specific date)"
        required_columns: ["date", "close_price"]
        sql: "SELECT date, close_price FROM stock_prices WHERE symbol = '{ticker}' AND date = '{start_date}';"
        intent_keywords: ["closing price", "price on"]
      - name: "company_info"
        description: "Retrieve company information"
        required_columns: ["symbol", "name", "sector", "market_cap"]
        sql: "SELECT symbol, name, sector, market_cap FROM companies WHERE symbol = '{ticker}';"
        intent_keywords: ["company info", "description"]

  - vis_type: "line_chart"
    description: "Line chart for time series data"
    columns:
      - name: "x_col"
        description: "The column representing the x-axis, typically a date or time series"
        intent_keywords: ["date", "time", "month"]
      - name: "y_col"
        description: "The primary column representing the y-axis, typically a numeric value"
        intent_keywords: ["close_price", "volume", "price"]
      - name: "additional_lines"
        description: "Additional columns to plot as separate lines on the chart (e.g., rolling averages)"
        intent_keywords: ["rolling_avg", "rolling_average", "moving_average"]
    templates:
      - name: "daily_closing_price_time_series"
        description: "Time series of closing prices for a company within a date range"
        required_columns: ["date", "close_price"]
        sql: "SELECT date, close_price FROM stock_prices WHERE symbol = '{ticker}' AND date BETWEEN '{start_date}' AND '{end_date}' ORDER BY date;"
        intent_keywords: ["time series", "stock price"]
      - name: "time_series_volume"
        description: "Time series of trading volume for a company within a date range"
        required_columns: ["date", "volume"]
        sql: "SELECT date, volume FROM stock_prices WHERE symbol = '{ticker}' AND date BETWEEN '{start_date}' AND '{end_date}' ORDER BY date;"
        intent_keywords: ["trading volume", "volume", "daily trading volume"]

  - vis_type: "bar_chart"
    description: "Bar chart for categorical data"
    columns:
      - name: "category_col"
        description: "The column representing categories for the x-axis"
        intent_keywords: ["symbol", "sector", "industry"]
      - name: "value_col"
        description: "The column representing the values for the y-axis"
        intent_keywords: ["avg_close_price", "market_cap", "count"]
    templates:
      - name: "bar_chart_price"
        description: "Average closing price by symbol within a date range"
        required_columns: ["symbol", "avg_close_price"]
        sql: "SELECT symbol, AVG(close_price) AS avg_close_price FROM stock_prices WHERE date BETWEEN '{start_date}' AND '{end_date}' GROUP BY symbol ORDER BY avg_close_price;"
        intent_keywords: ["average price", "bar chart"]

  - vis_type: "pie_chart"
    description: "Pie chart for proportions or counts"
    columns:
      - name: "category_col"
        description: "The column representing categories for the pie chart"
        intent_keywords: ["sector", "industry"]
      - name: "value_col"
        description: "The column representing the values for the pie chart"
        intent_keywords: ["proportion", "count", "market_cap"]
    templates:
      - name: "pie_chart_proportion"
        description: "Market cap proportions by sector"
        required_columns: ["sector", "proportion"]
        sql: "SELECT sector, SUM(market_cap) / (SELECT SUM(market_cap) FROM companies) * 100 AS proportion FROM companies GROUP BY sector ORDER BY proportion DESC LIMIT 5;"
        intent_keywords: ["proportions", "market cap by sector"]
      - name: "pie_chart_count"
        description: "Distribution of companies by sector with count"
        required_columns: ["sector", "count"]
        sql: "SELECT sector, COUNT(*) AS count FROM companies GROUP BY sector ORDER BY count DESC LIMIT 5;"
        intent_keywords: ["distribution", "count by sector"]

  - vis_type: "histogram"
    description: "Histogram for visualizing data frequency"
    columns:
      - name: "value_col"
        description: "The column representing the values for the histogram"
        intent_keywords: ["daily_return", "returns"]
    templates:
      - name: "daily_returns_histogram"
        description: "Daily returns for a company within a date range for histogram"
        required_columns: ["daily_return"]
        sql: "SELECT (close_price - LAG(close_price) OVER (PARTITION BY symbol ORDER BY date)) / LAG(close_price) OVER (PARTITION BY symbol ORDER BY date) AS daily_return FROM stock_prices WHERE symbol = '{ticker}' AND date BETWEEN '{start_date}' AND '{end_date}';"
        intent_keywords: ["daily returns", "returns", "histogram"]

  - vis_type: "boxplot"
    description: "Boxplot for visualizing data distribution"
    columns:
      - name: "group_col"
        description: "The column representing the grouping for the boxplot"
        intent_keywords: ["date", "month"]
      - name: "value_col"
        description: "The column representing the values for the boxplot"
        intent_keywords: ["daily_return", "close_price"]
      - name: "group_transform"
        description: "Optional transformation for the group column (e.g., convert date to month)"
        intent_keywords: ["to_month"]
    templates:
      - name: "daily_returns_boxplot"
        description: "Daily returns for a company within a date range for boxplot"
        required_columns: ["date", "daily_return"]
        sql: "SELECT date, (close_price - LAG(close_price) OVER (PARTITION BY symbol ORDER BY date)) / LAG(close_price) OVER (PARTITION BY symbol ORDER BY date) AS daily_return FROM stock_prices WHERE symbol = '{ticker}' AND date BETWEEN '{start_date}' AND '{end_date}' ORDER BY date;"
        intent_keywords: ["daily returns", "returns", "boxplot"]
      - name: "monthly_prices_boxplot"
        description: "Monthly closing prices for a company within a date range"
        required_columns: ["month", "close_price"]
        sql: "SELECT TO_CHAR(date, 'YYYY-MM') AS month, close_price FROM stock_prices WHERE symbol = '{ticker}' AND date BETWEEN '{start_date}' AND '{end_date}' ORDER BY date;"
        intent_keywords: ["monthly prices", "prices", "boxplot"]

  - vis_type: "scatter"
    description: "Scatter plot for visualizing relationships"
    columns:
      - name: "x_col"
        description: "The column representing the x-axis for the scatter plot"
        intent_keywords: ["avg_daily_volume", "volume"]
      - name: "y_col"
        description: "The column representing the y-axis for the scatter plot"
        intent_keywords: ["avg_closing_price", "close_price"]
      - name: "label_col"
        description: "The column representing labels for the scatter points"
        intent_keywords: ["symbol"]
    templates:
      - name: "scatter_volume_price"
        description: "Average daily volume vs closing price for companies within a date range"
        required_columns: ["avg_daily_volume", "avg_closing_price"]
        sql: "SELECT symbol, AVG(volume) AS avg_daily_volume, AVG(close_price) AS avg_closing_price FROM stock_prices WHERE date BETWEEN '{start_date}' AND '{end_date}' GROUP BY symbol ORDER BY avg_daily_volume, avg_closing_price;"
        intent_keywords: ["daily volume", "volume vs price", "scatter"]

  - vis_type: "heatmap"
    description: "Heatmap for visualizing correlation matrix of daily returns"
    columns:
      - name: "columns"
        description: "Dynamic columns for correlation matrix (e.g., aapl_msft, aapl_jpm)"
        intent_keywords: ["correlation", "returns"]
    templates:
      - name: "heatmap_returns"
        description: "Correlation matrix of daily returns between companies"
        required_columns: []
        sql: |
          WITH daily_returns AS (
            SELECT 
              date,
              {tickers_columns}
            FROM stock_prices
            WHERE symbol IN ({tickers}) 
              AND date BETWEEN '{start_date}' AND '{end_date}'
            GROUP BY date
            ORDER BY date
          )
          SELECT 
            {correlation_columns}
          FROM daily_returns
          WHERE {not_null_conditions};
        intent_keywords: ["correlation", "heatmap", "returns"]